version: '3'

services:
  db:
    container_name: postgresql
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data
       - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@live.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin

# volumes:
#   postgres-db:
#     external: true
      
